apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flaskapi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/VenkataKachana/FlaskAPI.git'  # Corrected Git URL format
    targetRevision: main
    path: Infra # Path to the directory containing your deployment YAML files
  destination:
    server: 'https://kubernetes.default.svc'  # Your Kubernetes API server URL
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true     
