apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          imagePullPolicy: Always
          image: dockerimageregistrytest.azurecr.io/flask-app:latest
          ports:
            - containerPort: 80