name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
    
    - name: Log into registry
      uses: docker/login-action@v1
      #uses: docker/login-action@v2
      with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag flask-app:latest
          docker tag flask-app:latest nextopsacr03.azurecr.io/flask-app:latest
          docker push nextopsacr03.azurecr.io/flask-app:latest

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: 'Change working directory'
      run: cd Terraform
        
    - name: 'Terraform Execution'
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      run: terraform init
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
