name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
    
    - name: Log into registry
      uses: docker/login-action@v1
      #uses: docker/login-action@v2
      with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag flask-app:latest
          docker tag flask-app:latest nextopsacr03.azurecr.io/flask-app:latest
          docker push nextopsacr03.azurecr.io/flask-app:latest
       
    - name: 'Terraform Execution'
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./Terraform # Use your environment folder
      shell: bash

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}

    - name: Terraform Apply
      run: terraform apply --auto-approve
      working-directory: ./Terraform # Use your environment folder
      shell: bash  
