name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v3
    
    - name: Log into registry
      uses: docker/login-action@v1
      #uses: docker/login-action@v2
      with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask-app:$(date +%s)
    
